### PR TITLE
add support for AlmaLinux & Rocky

### PR DESCRIPTION
**Pull request by jhoblitt**
Manually tested as working on an AlmaLinux 8.6 instance.

### CODE REVIEW

**Comment by jhoblitt** [comment]
I have added a commit to fix the spec for the change in behavior of `ensure_packages()`.

**Comment by trevor-vaughan** [comment]
@jhoblitt Tests check out. Added a PR with updated nodesets, etc...

**Comment by trevor-vaughan** [comment]
@jhoblitt Nope, I just need to fire off the GitLab tests and make sure everything works.

**Comment by trevor-vaughan** [comment]
PE FIPS test failed with a timeout. Need to add CPUs after this PR goes through.

**Pull request merged**
